Timer format
Crystalwarrior/KFO-Server pull request #142
Opened 2024-05-21 19:21 UTC by EstatoDeviato

2024-05-26 20:14 UTC, Crystalwarrior requested changes
Looks good, only 1 change requested to the /format_timer command before merge

2024-05-26 20:14 UTC, Crystalwarrior commented on server/commands/roleplay.py
> +                c.send_command("TF", args[0], args[1], current_time)
Maybe re-use send_timer_set_time instead?

2024-05-26 20:14 UTC, Crystalwarrior commented
Oh yeah-- can you also add a documentation/commands.md entry and any aliases to the config_sample?

2024-06-11 18:13 UTC, EstatoDeviato commented
Okay I've added stuff to command aliases and to documentation

2024-10-04 11:22 UTC, Crystalwarrior commented on server/client_manager.py
> +                    self.send_command("TF", timer_id, timer.format, new_time)
does DRO support timer formatting or is this just a KFO-Client feature we came up with? I'll double-check.

2024-10-04 11:22 UTC, Crystalwarrior approved these changes
Cool and Good, just testing left

2024-12-27 02:51 UTC, Crystalwarrior commented
Closed by #145

2024-12-27 02:51 UTC, closed without merging