Server count and mod count
Crystalwarrior/KFO-Server pull request #40
Opened 2022-02-18 01:13 UTC by EstatoDeviato

2022-03-01 01:50 UTC, Crystalwarrior commented
I'm not sure I like people knowing how many mods are online, especially on KFO since technically any mod can just pop in via mod password, enforce shit, and pop out.
I also want people to use the modcall button even if no mods are online since the modcall button does connect to the Discord.

2022-03-01 07:38 UTC, EstatoDeviato commented
If you want, I can remove mod_count

2022-03-04 14:14 UTC, EstatoDeviato reviewed
Remove mod_count

2022-03-29 14:30 UTC, Crystalwarrior requested changes
I suggest to keep each PR to just 1 specific thing, the change to display server name in area list is separate from the PR's title

2022-03-29 14:30 UTC, Crystalwarrior commented on server/client_manager.py
> +                            f"{self.server.config['masterserver_name']}\n Users Online: {server_count}\n Double-Click me to see Areas\n _______",
Not sure I like this. What if masterserver_name is not defined, or the server is not listed on the master server?

2022-03-29 14:30 UTC, Crystalwarrior commented on server/client_manager.py
> +                        f"{self.server.config['masterserver_name']}\n Users Online: {server_count}\n Double-Click me to see Areas\n _______",
Not sure I like this. What if masterserver_name is not defined, or the server is not listed on the master server?

2023-06-21 19:55 UTC, Crystalwarrior commented
Stale cuz I suck :( reopen if updated

2023-06-21 19:55 UTC, closed without merging